apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: "https://github.com/YOUR_GITHUB_USERNAME/express-app-helm.git"
    targetRevision: main
    path: .
    helm:
      values: |
        image:
          repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_AWS_REGION.amazonaws.com/express-app
          tag: latest
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
